config/routes.rb
Rails.application.routes.draw do

  resources :users
  resources :rides
  devise_for :users
  root to: "homes#top"
  get "about" => "homes#about"
  get "how_to" => "homes#how_to"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ride.rb
class Ride < ApplicationRecord
  belongs_to :user
  has_many :rider_comments, dependent: :destroy
  attachment :image
end

app/models/rider_comment.rb
class RiderComment < ApplicationRecord
  belongs_to :user
  belongs_to :ride
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :rides, dependent: :destroy
  has_many :rider_comments, dependent: :destroy

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end

  def how_to
  end
end

app/controllers/rides_controller.rb
class RidesController < ApplicationController
  def index
  end

  def show
  end

  def new
  end

  def edit
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end

  def show
  end

  def edit
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/rides_helper.rb
module RidesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/homes/about.html.erb
<h1>Homes#about</h1>
<p>Find me in app/views/homes/top.html.erb</p>

app/views/homes/how_to.html.erb
<h1>Homes#howto</h1>
<p>Find me in app/views/homes/top.html.erb</p>

app/views/homes/top.html.erb
<header>
    <nav class= "navbar navbar-expand-lg navbar-red bg-dark">
        <div class="container">
            <span>RIDEEERs</span>
            <div class="collapse navbar-collapse" id="navbarNavDropdown">
                <ul class="navbar-nav ml-auto">
                    <li><%=link_to "Home", root_path, class:"fas fa-campground nav-link text-light" %></li>
                    <li><%=link_to "About", about_path, class:"fas fa-atlas nav-link text-light"%></li>
                    <li><%=link_to "How to", how_to_path, class:"fas fa-question-circle"%></li>
                    <li><%=link_to "Login", user_session_path %></li>
                    <li><%=link_to "Sign up", new_user_registration_path %></li>

                </ul>
            </div>
        </div>
    </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Riders</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/rides/edit.html.erb
<h1>Rides#edit</h1>
<p>Find me in app/views/rides/edit.html.erb</p>

app/views/rides/index.html.erb
<h1>Rides#index</h1>
<p>Find me in app/views/rides/index.html.erb</p>

app/views/rides/new.html.erb
<h1>Rides#new</h1>
<p>Find me in app/views/rides/new.html.erb</p>

app/views/rides/show.html.erb
<h1>Rides#show</h1>
<p>Find me in app/views/rides/show.html.erb</p>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>